-- MySQL Script generated by MySQL Workbench
-- 03/14/17 18:29:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema famiday
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `famiday` ;

-- -----------------------------------------------------
-- Schema famiday
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `famiday` DEFAULT CHARACTER SET utf8 ;
USE `famiday` ;

-- -----------------------------------------------------
-- Table `famiday`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famiday`.`user` (
  `userid` VARCHAR(32) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `datecreation` DATE NOT NULL,
  `online` TINYINT(1) NOT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `famiday`.`family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famiday`.`family` (
  `idfamily` VARCHAR(32) NOT NULL,
  `familyname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfamily`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `famiday`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famiday`.`event` (
  `eventid` VARCHAR(32) NOT NULL,
  `eventname` VARCHAR(45) NOT NULL,
  `eventstart` DATETIME NOT NULL,
  `eventend` DATETIME NOT NULL,
  `location` VARCHAR(255) NULL,
  `participant` VARCHAR(255) NOT NULL,
  `summary` LONGTEXT NULL,
  `last_modif` DATE NULL,
  `frequence` VARCHAR(45) NULL,
  `until` DATETIME NULL,
  PRIMARY KEY (`eventid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `famiday`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famiday`.`calendar` (
  `idcalendar` VARCHAR(32) NOT NULL,
  `calendar` LONGTEXT NOT NULL,
  `user_calendar` VARCHAR(32) NULL,
  PRIMARY KEY (`idcalendar`),
  INDEX `fk_calendar_user1_idx` (`user_calendar` ASC),
  CONSTRAINT `fk_calendar_user1`
    FOREIGN KEY (`user_calendar`)
    REFERENCES `famiday`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `famiday`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famiday`.`message` (
  `idmessage` VARCHAR(32) NOT NULL,
  `object` VARCHAR(60) NOT NULL,
  `message` LONGTEXT NOT NULL,
  `datemessage` DATETIME NOT NULL,
  `trashed` TINYINT(1) NOT NULL,
  `read` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idmessage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `famiday`.`personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famiday`.`personne` (
  `idpersonne` VARCHAR(32) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `datebirth` DATE NULL,
  `phone` INT NOT NULL,
  `adress` VARCHAR(70) NOT NULL,
  `about` LONGTEXT NULL,
  `userid` VARCHAR(32) NULL,
  PRIMARY KEY (`idpersonne`),
  INDEX `fk_personne_user1_idx` (`userid` ASC),
  CONSTRAINT `fk_personne_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `famiday`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `famiday`.`members_of_family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famiday`.`members_of_family` (
  `familyid` VARCHAR(32) NOT NULL,
  `responsible` TINYINT(1) NOT NULL,
  `personne_idpersonne` VARCHAR(32) NOT NULL,
  INDEX `fk_members_of_family_family1_idx` (`familyid` ASC),
  INDEX `fk_members_of_family_personne1_idx` (`personne_idpersonne` ASC),
  CONSTRAINT `fk_members_of_family_family1`
    FOREIGN KEY (`familyid`)
    REFERENCES `famiday`.`family` (`idfamily`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_of_family_personne1`
    FOREIGN KEY (`personne_idpersonne`)
    REFERENCES `famiday`.`personne` (`idpersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `famiday`.`relations_of_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famiday`.`relations_of_events` (
  `eventid` VARCHAR(32) NOT NULL,
  `calendarid` VARCHAR(32) NOT NULL,
  INDEX `fk_relations_of_events_event1_idx` (`eventid` ASC),
  INDEX `fk_relations_of_events_calendar1_idx` (`calendarid` ASC),
  CONSTRAINT `fk_relations_of_events_event1`
    FOREIGN KEY (`eventid`)
    REFERENCES `famiday`.`event` (`eventid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relations_of_events_calendar1`
    FOREIGN KEY (`calendarid`)
    REFERENCES `famiday`.`calendar` (`idcalendar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `famiday`.`message_sent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famiday`.`message_sent` (
  `from` VARCHAR(32) NOT NULL,
  `to` VARCHAR(32) NOT NULL,
  `message` VARCHAR(32) NOT NULL,
  INDEX `fk_message_sent_user1_idx` (`from` ASC),
  INDEX `fk_message_sent_user2_idx` (`to` ASC),
  INDEX `fk_message_sent_message1_idx` (`message` ASC),
  CONSTRAINT `fk_message_sent_user1`
    FOREIGN KEY (`from`)
    REFERENCES `famiday`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_sent_user2`
    FOREIGN KEY (`to`)
    REFERENCES `famiday`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_sent_message1`
    FOREIGN KEY (`message`)
    REFERENCES `famiday`.`message` (`idmessage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
